# Generated by Django 4.1.7 on 2023-03-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_post_created_by_post_tag_name_post_tag_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
