# Generated by Django 4.1.7 on 2023-03-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_image_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag_weight',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('OTHERS', 'Others')], help_text='User Type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(help_text='Tag', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='adminapp.tag'),
        ),
    ]
